name: Demo
on:
  push:
    branches:
      - demo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1

      - run: npm install

      - name: build library
        run: npm run build -- --prod

      - name: build demo
        run: npm run build -- --prod --project=demo-app

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/demo-app
