name: Test
on:
  push:
    branches:
      - v*
      - demo

  pull_request:
    branches:
      - main
      - demo
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - run: npm install

      - name: run linter
        run: npm run lint

      - name: build library
        run: npm run build -- --prod

      - name: run library tests
        run: npm run test

      - name: run demo tests
        run: npm run test:demo
